import { Link } from 'react-router-dom';
import Reveal from '../components/ui/Reveal';
import TiltCard from '../components/ui/TiltCard';
import { SOURCE_TEXTS } from '../data/content';

export default function Library() {
  return (
    <div className="page library">
      <header className="page-head">
        <Reveal>
          <span className="eyebrow">
            <span className="eyebrow-dot" />
            Reference library
          </span>
          <h1>The texts behind the guidance</h1>
          <p className="page-lead">
            These classical works form the intellectual foundation of Ayurveda. HerbiGPT
            draws on summarized principles from this tradition and points back to it —
            it does not reproduce the texts themselves. Consider this a reading list and
            a bit of historical context.
          </p>
          <div className="library-note glass">
            <strong>On honesty:</strong> answers are generated by a language model and
            grounded by a small, hand-written knowledge base. The books below inspire and
            inform that base; they are not ingested in full.
          </div>
        </Reveal>
      </header>

      <div className="shelf">
        {SOURCE_TEXTS.map((s, i) => (
          <Reveal key={s.title} delay={i * 0.05}>
            <TiltCard className="book glass" intensity={6}>
              <div className="book-cover" style={{ background: s.accent }}>
                <span className="book-cover-sanskrit">{s.sanskrit}</span>
                <span className="book-cover-title">{s.title}</span>
              </div>
              <div className="book-body">
                <div className="book-attr">{s.attribution}</div>
                <div className="book-period">{s.period}</div>
                <p className="book-blurb">{s.blurb}</p>
                <div className="book-why">
                  <span className="book-why-label">Why it matters here</span>
                  <p>{s.importance}</p>
                </div>
                <a className="book-link" href={s.link} target="_blank" rel="noreferrer">
                  Read more ↗
                </a>
              </div>
            </TiltCard>
          </Reveal>
        ))}
      </div>

      <Reveal>
        <div className="closing glass">
          <h2>Curious how it’s applied?</h2>
          <p>Ask a question and watch which references inform the answer.</p>
          <Link to="/chat" className="btn btn-primary btn-lg">Open the chat</Link>
        </div>
      </Reveal>
    </div>
  );
}
